version: '3'
services:
  jenkins:
    container_name: "jenkins"
    image: "jenkins/jenkins:latest"
    ports:
    - "8081:8080"
    - "50000:50000"
    volumes:
    - "/root/docker/compose/jenkins/jenkins_home:/var/jenkins_home"