version: "3"
services:
  gitlab:
    container_name: "gitlab"
    image: 'gitlab/gitlab-ee:latest'
    #restart: always
    #hostname: 'gitlab.example.cn'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.102.52:9090'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
    - '9090:9090'
    - '2224:22'
    volumes:
    - '/srv/gitlab/config:/etc/gitlab:Z'
    - '/srv/gitlab/logs:/var/log/gitlab:Z'
    - '/srv/gitlab/data:/var/opt/gitlab:Z'